version: '3'
services:
  nginx:
    image: nginx:1.13.9-alpine
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./contents/html:/var/www/html

  php:
    build: ./php
    env_file: ./mysql/.env_sample
    environment:
      DATABASE_HOST: mysql
    depends_on:
      - mysql
    volumes:
      - ./contents/html:/var/www/html

  mysql:
    image: mysql:5.7.21
    env_file: ./mysql/.env_sample
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/initial.sql:/docker-entrypoint-initdb.d/initial.sql

volumes:
  est-data:
